version = "3.8.3"
maxColumn = 120
align.preset = most
runner.dialect = scala213
fileOverride {
  "glob:**/src/test/scala/org/jetbrains/plugins/scala/**"
  runner.dialect = scala213
}
project.includePaths = [
  "src/main/scala/**"
  "src/test/scala/com/**"
  "build.sbt"
  "project/*.scala"
]
project.excludePaths = [
  "src/test/scala/org/jetbrains/plugins/scala/**"
  "target/**"
]
rewrite.scala3.removeOptionalBraces.enabled = false
runner.dialect = scala213
