dogfood.sbt.version=1.10.7
ide.probe.version=0.53.0
intellij.build=261.26222.65
intellij.product.code=IC
intellij.release=2026.1.4
java.bytecode.release=17
jbr.java.runtime.version=25.0.3+9-b329.124
jbr.java.vendor=JetBrains s.r.o.
jbr.java.vendor.version=JBR-25.0.3+9-329.124-jcef
sbt.version=1.11.7
scala.compiler.version=3.7.4
scala.plugin.id=org.intellij.scala
scala.plugin.version=2026.1.20
testkit.scala.version=2.13.16
